version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/html  
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    command: bash -c "mkdir -p /var/www/html && cp -r /var/www/html/* /data && apache2-foreground"