version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-app
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge